### ISSUE TITLE
Coarse2FineTwoFrames

### ISSUE THREAD

**Issue by pasbi** [sammy-su/Ego-Engagement#1]
In `computeflow.m`, you call the function `Coarse2FineTwoFrames`.
But on my machine, matlab does not find this function. How to fix that?

I found this: https://people.csail.mit.edu/celiu/OpticalFlow/
However, I have problems to use it and I wonder if I'm on the right way.

**Comment by sammy-su** [comment]
Yes, Coarse2FineTwoFrames is a function in the OpticalFlow package, so you have to compile the code and add the path to computeflow.m (mex_dir).
